package model.pojo;
// Generated Feb 28, 2016 2:13:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private int categoryId;
     private String categoryName;
     private Set documents = new HashSet(0);

    public Category() {
    }

	
    public Category(int categoryId, String categoryName) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
    }
    public Category(int categoryId, String categoryName, Set documents) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
       this.documents = documents;
    }
   
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Set getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Set documents) {
        this.documents = documents;
    }




}


