package model.pojo;
// Generated Feb 28, 2016 2:13:37 PM by Hibernate Tools 4.3.1

/**
 * DocumentDetail generated by hbm2java
 */
public class DocumentDetail implements java.io.Serializable {

    private int contentId;
    private Document document;
    private String contentText;

    public DocumentDetail() {
    }

    public DocumentDetail(int contentId) {
        this.contentId = contentId;
    }

    public DocumentDetail(int contentId, Document document, String contentText) {
        this.contentId = contentId;
        this.document = document;
        this.contentText = contentText;
    }

    public int getContentId() {
        return this.contentId;
    }

    public void setContentId(int contentId) {
        this.contentId = contentId;
    }

    public Document getDocument() {
        return this.document;
    }

    public void setDocument(Document document) {
        this.document = document;
    }

    public String getContentText() {
        return this.contentText;
    }

    public void setContentText(String contentText) {
        this.contentText = contentText;
    }
}
