package model.pojo;
// Generated Feb 28, 2016 2:13:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Document generated by hbm2java
 */
public class Document  implements java.io.Serializable {


     private int documentId;
     private Category category;
     private FormatFile formatFile;
     private Users user;
     private String documentName;
     private Date dateIssued;
     private Date signedDate;
     private String whoIssuedRegulation;
     private String signer;
     private Date fromDate;
     private Date toDate;
     private String documentNo;
     private String path;
     private Date timeUpload;
     private Set contentOfDocuments = new HashSet(0);

    public Document() {
    }

	
    public Document(int documentId, String documentName) {
        this.documentId = documentId;
        this.documentName = documentName;
    }
    public Document(int documentId, Category category, FormatFile formatFile, Users user, String documentName, Date dateIssued, Date signedDate, String whoIssuedRegulation, String signer, Date fromDate, Date toDate, String documentNo, String path, Date timeUpload, Set contentOfDocuments) {
       this.documentId = documentId;
       this.category = category;
       this.formatFile = formatFile;
       this.user = user;
       this.documentName = documentName;
       this.dateIssued = dateIssued;
       this.signedDate = signedDate;
       this.whoIssuedRegulation = whoIssuedRegulation;
       this.signer = signer;
       this.fromDate = fromDate;
       this.toDate = toDate;
       this.documentNo = documentNo;
       this.path = path;
       this.timeUpload = timeUpload;
       this.contentOfDocuments = contentOfDocuments;
    }
   
    public int getDocumentId() {
        return this.documentId;
    }
    
    public void setDocumentId(int documentId) {
        this.documentId = documentId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    
    public FormatFile getformatfile() {
        return this.formatFile;
    }
    
    public void setformatfile(FormatFile formatFile) {
        this.formatFile = formatFile;
    }
    
    public Users getUser() {
        return this.user;
    }
    
    public void setUser(Users user) {
        this.user = user;
    }
    public String getDocumentName() {
        return this.documentName;
    }
    
    public void setDocumentName(String documentName) {
        this.documentName = documentName;
    }
    public Date getDateIssued() {
        return this.dateIssued;
    }
    
    public void setDateIssued(Date dateIssued) {
        this.dateIssued = dateIssued;
    }
    public Date getSignedDate() {
        return this.signedDate;
    }
    
    public void setSignedDate(Date signedDate) {
        this.signedDate = signedDate;
    }
    public String getWhoIssuedRegulation() {
        return this.whoIssuedRegulation;
    }
    
    public void setWhoIssuedRegulation(String whoIssuedRegulation) {
        this.whoIssuedRegulation = whoIssuedRegulation;
    }
    public String getSigner() {
        return this.signer;
    }
    
    public void setSigner(String signer) {
        this.signer = signer;
    }
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    public Date getToDate() {
        return this.toDate;
    }
    
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
    public String getDocumentNo() {
        return this.documentNo;
    }
    
    public void setDocumentNo(String documentNo) {
        this.documentNo = documentNo;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public Date getTimeUpload() {
        return this.timeUpload;
    }
    
    public void setTimeUpload(Date timeUpload) {
        this.timeUpload = timeUpload;
    }
    public Set getContentOfDocuments() {
        return this.contentOfDocuments;
    }
    
    public void setContentOfDocuments(Set contentOfDocuments) {
        this.contentOfDocuments = contentOfDocuments;
    }
}


