package model.pojo;
// Generated Feb 28, 2016 2:13:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * FormatFile generated by hbm2java
 */
public class FormatFile  implements java.io.Serializable {


     private int formartFileId;
     private Set<Document> documents = new HashSet<Document>(0);
     private String formartFileName;

    public FormatFile() {
    }

    public FormatFile(int formartFileId, String formartFileName, Set<Document> documents) {
       this.formartFileId = formartFileId;
       this.formartFileName = formartFileName;
       this.documents = documents;
    }
   
    public int getFormartFileId() {
        return this.formartFileId;
    }
    
    public void setFormartFileId(int formartFileId) {
        this.formartFileId = formartFileId;
    }
    public String getFormartFileName() {
        return this.formartFileName;
    }
    
    public void setFormartFileName(String formartFileName) {
        this.formartFileName = formartFileName;
    }
  public String getDocuments() {
        return this.formartFileName;
    }
    
    public void setDocuments(Set<Document> documents) {
        this.documents = documents;
    }
}


